/**
 * @module core/cookies
 * Netscape-format cookie file parser and serialiser.
 *
 * @author NeoKEX (https://github.com/NeoKEX)
 * @license MIT
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';

export class CookieManager {
  /**
   * Parse a Netscape-format cookie file into a key/value map.
   */
  static parseNetscape(content: string): Record<string, string> {
    const cookies: Record<string, string> = {};

    for (let line of content.split('\n')) {
      line = line.trim();
      if (!line) continue;
      if (line.startsWith('#HttpOnly_')) line = line.slice(10);
      else if (line.startsWith('#')) continue;

      const parts = line.split(/\s+/);
      if (parts.length >= 7) {
        const name  = parts[5].trim();
        const value = parts[6].trim();
        if (name && value) cookies[name] = value;
      }
    }

    return cookies;
  }

  /**
   * Load cookies from a Netscape-format file on disk.
   * Throws if the file does not exist.
   */
  static loadFromFile(filePath: string): Record<string, string> {
    if (!existsSync(filePath)) throw new Error(`Cookie file not found: ${filePath}`);
    return CookieManager.parseNetscape(readFileSync(filePath, 'utf-8'));
  }

  /**
   * Serialise a cookie map back to a Netscape-format file.
   */
  static saveToFile(
    filePath: string,
    cookies: Record<string, string>,
    domain = '.instagram.com',
  ): void {
    const expiry = Math.floor(Date.now() / 1000) + 365 * 86400;
    const lines  = [
      '# Netscape HTTP Cookie File',
      '# Generated by ica-neokex — https://github.com/NeoKEX/ica-neokex',
      '# Edit at your own risk.',
      '',
      ...Object.entries(cookies).map(([name, value]) =>
        [domain, 'TRUE', '/', 'TRUE', expiry, name, value].join('\t'),
      ),
    ];
    writeFileSync(filePath, lines.join('\n'), 'utf-8');
  }

  /**
   * Render a cookie map as a `Cookie` header string.
   */
  static toString(cookies: Record<string, string>): string {
    return Object.entries(cookies).map(([k, v]) => `${k}=${v}`).join('; ');
  }
}
